---
# tasks file for fireup-elasticsearch
- name: Create Elastic Search container.
  docker_container:
    name: elasticsearch
    image: elasticsearch
    state: started
    volumes: /opt/volume/esdata/node1
    exposed_ports:
      - 9200
      - 9300
    env:
      Des.node.name: Node1

- name: Get the Container IDs for any Elasticsearch containers
  script: ./files/scripts/elastic-search-container-ids
  register: elastic_search_ids

- debug: var=elastic_search_ids

- name: Install Kopf into the Elasticsearch containers
  shell:  docker exec -i {{ item }} bin/plugin install lmenezes/elasticsearch-kopf 
  with_items: "{{ elastic_search_ids.stdout_lines[0] }}"

